server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # 1. User Auth Service
        - id: user-auth-service
          uri: http://user-auth-service:8081
          predicates:
            - Path=/api/v1/auth/**

        # 2. Product Catalog Service
        - id: product-catalog-service
          uri: http://product-catalog-service:8082
          predicates:
            - Path=/api/v1/products/**

        # 3. Order Processing Service
        - id: order-processing-service
          uri: http://order-processing-service:8083
          predicates:
            - Path=/api/v1/orders/**

        # 4. Inventory Service
        - id: inventory-service
          uri: http://inventory-service:8084
          predicates:
            - Path=/api/v1/inventory/**

        # 5. Notification Logging Service
        - id: notification-logging-service
          uri: http://notification-logging-service:8085
          predicates:
            - Path=/api/v1/logs/**